ai:
  server:
    recommend-url: https://travel-recommend-api-98044284658.asia-northeast3.run.app/ai/recommend
    carbon-url: https://carbon-api-340794693904.asia-northeast3.run.app/ai/carbon/estimate
    verify-image-url: https://www.ecovel.site/ai/verify-image
    quiz-url: https://www.ecovel.site/quiz

server:
  port: 8080


spring:
  datasource:
    url: jdbc:mysql://35.225.5.236:3306/ecovel
    username: root
    password: Jimin@1019!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  security:
    jwt:
      secret: yourLongSecretKeyHere

  web:
    resources:
      static-locations: file:uploads/