ai:
  server:
    recommend-url: https://travel-recommend-api-98044284658.asia-northeast3.run.app/ai/recommend
    carbon-url: http://localhost:8000/ai/carbon/estimate
    verify-image-url: http://your-ai-server.com/ai/verify-image

spring:
  datasource:
    url: jdbc:mysql://34.60.22.8:3306/ecovel
    username: root
    password: Jimin@1019!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  security:
    jwt:
      secret: yourLongSecretKeyHere

  web:
    resources:
      static-locations: file:uploads/